<?php

namespace app\backend\modules\appointment\controllers;

use app\models\TAppointment;
use yii\web\Controller;
use app\backend\components\BaseController;
use Yii;
use yii\data\Pagination;
use yii\helpers\Json;

/**
 * Default controller for the `appointment` module
 */
class DefaultController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['css'] = [
            'global/plugins/layer/skin/default/layer.css',
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.css',
            'global/plugins/fancybox/source/jquery.fancybox.css',
            'global/plugins/bootstrap-fileinput/fileinput.css',
        ];

        $this->data['js'] = [
            'global/plugins/layer/layer.js',
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.js',
            'backend/appointment/default.js',
        ];
    }
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->data['search_attributes'] =  $params = Yii::$app->request->get();
        $pageIndex = Yii::$app->request->get('page',1);
        $model = TAppointment::getList(TAppointment::search($params),$pageIndex,$this->pageSize);
        $user_id = Yii::$app->session['user_id'];
        $this->data['count'] = $model['count'];
        $this->data['dataProvider'] = $model['list'];

        $this->data['pages'] = new Pagination(
            [
                'totalCount' => $this->data['count'],
                'defaultPageSize'=>$pageIndex,
                'pageSizeLimit'=>[$this->pageSize,$this->pageSize]
            ]
        );
        return $this -> render('index',$this->data);
    }
    /**
     * 删除轮播图
     */
    public function actionDelete()
    {
        $this->data['params'] = \yii::$app->request->post();
        if(TAppointment::findOne($this->data['params']['id'])->delete()){
            return Json::encode(['code'=>200, 'msg'=>'删除成功']);
        }else{
            return Json::encode(['code'=>400, 'msg'=>'删除失败']);
        }
    }
    /**
     * 批量删除
     * @param banners_id
     * @reutrn array
     */
    public function actionBatchDel()
    {

        $banners_id = trim(Yii::$app->request->post('banners_id'), ',');
        $banners_id = explode(',',$banners_id);
        if (!$banners_id) return Json::encode(['code'=>500, 'msg'=>'没有获取请求的ID']);
        foreach($banners_id as $v){
            $model = TAppointment::findOne($v)->delete();
        }
        return Json::encode(['code'=>200]);
    }


    public function actionHandle(){
        $post = Yii::$app->request->post();
        $id = Yii::$app->request->get('id');
        $this->data['id'] = $id;
        $this->data['row'] =  TAppointment::findOne($id);
        if($post){
            $model = TAppointment::findOne($post['id']);
            $model->memo = $post['memo'];
            $model->update_time = time();
            $model->status = '2';
            if($model->save()){
                return Json::encode(['code'=>200,'msg'=>'处理成功']);exit;
            }else{
                return Json::encode(['code'=>400,'msg'=>'处理失败']);exit;
            }
        }
        return $this->renderAjax('handle',$this->data);
    }
}
