<?php

namespace app\backend\modules\banner\controllers;

use app\backend\components\BaseController;
use app\models\Common;
use app\models\TBanner;
use yii\web\Controller;
use Yii;
use yii\data\Pagination;
use yii\helpers\Json;

/**
 * Default controller for the `banner` module
 */
class DefaultController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['css'] = [
            'global/plugins/layer/skin/default/layer.css',
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.css',
            'global/plugins/fancybox/source/jquery.fancybox.css',
            'global/plugins/bootstrap-fileinput/fileinput.css',
        ];

        $this->data['js'] = [
            'global/plugins/layer/layer.js',
            'global/plugins/bootstrap-fileinput/bootstrap-fileinput.js',
        ];
    }
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->data['search_attributes'] =  $params = Yii::$app->request->get();
        $pageIndex = Yii::$app->request->get('page',1);
        $model = TBanner::getList(TBanner::search($params),$pageIndex,$this->pageSize);
        $user_id = Yii::$app->session['user_id'];
        $this->data['count'] = $model['count'];
        $this->data['dataProvider'] = $model['list'];

        $this->data['pages'] = new Pagination(
            [
                'totalCount' => $this->data['count'],
                'defaultPageSize'=>$pageIndex,
                'pageSizeLimit'=>[$this->pageSize,$this->pageSize]
            ]
        );
        return $this -> render('index',$this->data);
    }
    /**
     *添加
     */
    public function actionCreate(){
        $post = Yii::$app->request->post('Banner');
        if($post){
            $post['img_url'] = Common::common($post['img_url'], 'banner');
            $model = new TBanner();
            $post['create_time'] = time();
            $model->attributes = $post;
            if($model->save()){
                $this->refresh('&ref_sub=200');
            }else{
                $this->refresh('&ref_sub=500');
            }
        }
        $this->data['action'] = 'create';
        return $this -> render('create',$this->data);
    }
    /**
     * 编辑
     */
    public function actionUpdate(){
        $id = Yii::$app->request->get('id');
        $attribute = Yii::$app->request->post('Banner');
        if($attribute){
            $model = TBanner::findOne($id);
            if (isset($attribute['img_url']) && $attribute['img_url']!=$model->img_url){//图片上传
                $attribute['img_url'] = Common::common($attribute['img_url'], 'banner');
            }
            $model->update_time = time();
            $model->name = $attribute['name'];
            $model->img_url = $attribute['img_url'];
            $model->link_url = $attribute['link_url'];
            $model->sort = $attribute['sort'];
            $submit = $model->save()?200:500;
            $this->refresh('&ref_sub='.$submit);
        }
        $this->data['row'] = TBanner::findOne($id);
        $this->data['action'] = 'update&id='.$id;
        return $this->render('create',$this->data);
    }
    /**
     * 删除轮播图
     */
    public function actionDelete()
    {
        $this->data['params'] = \yii::$app->request->get();
        if(TBanner::findOne($this->data['params']['id'])->delete()){
            return Json::encode(['code'=>200, 'msg'=>'删除成功']);
        }else{
            return Json::encode(['code'=>400, 'msg'=>'删除失败']);
        }
    }
    /**
     * 批量删除
     * @param banners_id
     * @reutrn array
     */
    public function actionBatchDel()
    {

        $banners_id = trim(Yii::$app->request->post('banners_id'), ',');
        $banners_id = explode(',',$banners_id);
        if (!$banners_id) return Json::encode(['code'=>500, 'msg'=>'没有获取请求的ID']);
        foreach($banners_id as $v){
            $model = TBanner::findOne($v)->delete();
        }
        return Json::encode(['code'=>200]);
    }
}
