<?php

namespace app\backend\modules\admin\controllers;
use app\backend\components\AppAdminAcl;
use app\backend\components\BaseController;
use app\models\TAdmin;
use Yii;

/**
 * Default controller for the `admin` module
 */
class AdminController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['js'] = array(
            'global/plugins/moment.min.js'
        );
    }
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->data['js'] = [
            'global/plugins/moment.min.js',
            'global/plugins/counterup/jquery.waypoints.min.js',
            'global/plugins/counterup/jquery.counterup.min.js',
            'global/plugins/bootstrap-daterangepicker/daterangepicker.min.js',
            'global/plugins/flot/jquery.flot.min.js',
            'global/plugins/flot/jquery.flot.categories.min.js',
            'backend/admin/default.js'
        ];
        $this->data['css'] = [
            'global/plugins/bootstrap-daterangepicker/daterangepicker.min.css',
            'global/plugins/fullcalendar/fullcalendar.min.css',
            'global/plugins/jqvmap/jqvmap/jqvmap.css',
        ];
        $this->getView()->title = '初始页';
        return $this->render('index', $this->data);
    }

}
