<?php

namespace app\backend\modules\admin\controllers;
use app\backend\components\AppAdminAcl;
use app\backend\components\BaseController;
use app\models\TAdmin;
use Yii;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['js'] = array(
            'global/plugins/moment.min.js'
        );
    }
    public $layout = '@app/backend/views/layouts/main_login';
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->data['js'] = [
            'global/plugins/moment.min.js',
            'global/plugins/counterup/jquery.waypoints.min.js',
            'global/plugins/counterup/jquery.counterup.min.js',
            'global/plugins/bootstrap-daterangepicker/daterangepicker.min.js',
            'global/plugins/flot/jquery.flot.min.js',
            'global/plugins/flot/jquery.flot.categories.min.js',
            'backend/admin/default.js'
        ];
        $this->data['css'] = [
            'global/plugins/bootstrap-daterangepicker/daterangepicker.min.css',
            'global/plugins/fullcalendar/fullcalendar.min.css',
            'global/plugins/jqvmap/jqvmap/jqvmap.css',
        ];
        $this->getView()->title = '初始页';
        return $this->render('index', $this->data);
    }
    /**
     * user login
     * @return string
     */
    public function actionLogin(){
        $this->data['js'] = array(
            /*begin validate*/
            'global/plugins/jquery-validation/js/jquery.validate.min.js',
            'global/plugins/jquery-validation/js/additional-methods.min.js',
            'global/plugins/select2/js/select2.full.min.js',
            /*end validate*/
            'pages/scripts/login.js'
        );
        $this->data['css'] = array(
            'pages/css/login.min.css'
        );
        $this->data['error'] = '';
        $params = Yii::$app->request->post('User');
        if($params){
            $model =  TAdmin::find()->where([
                'name'=>$params['name'],
                'password'=>md5(md5($params['password'])),
            ])->one();
            if(!$model) {
                $this->data['error'] = '用户名或密码错误';
            }
            else {
                $this->saveSession($model);
                TAdmin::updateAll(
                    [
                        'update_time'=>time(),
                        'login_ip'=>Yii::$app->request->userIP,
                        'login_count'=>$model->login_count + 1
                    ],
                    'user_id = :user_id',
                    [':user_id'=>$model['user_id']]
                );
                $this->redirect('?r=admin/admin/index');
            }
        }
        return $this->render('login', $this->data);
    }
    /**
     * 保存用户信息到session
     * @param $memberParams
     */
    protected function saveSession($memberParams)
    {
        Yii::$app->session['user_id'] = $memberParams['user_id'];
        Yii::$app->session['name'] = $memberParams['name'];
        Yii::$app->session['acl'] = AppAdminAcl::$aclList;

    }
    /**
     * 退出 清除缓存
     */
    public function actionLogout()
    {
        Yii::$app->session->remove('user_id');
        Yii::$app->session->remove('name');
        Yii::$app->session->remove('acl');

        $this->redirect('?r=admin/default/login');
    }
}
