<?php

namespace app\api\modules\site\controllers;

use app\backend\components\BaseController;
use app\models\TAppointment;
use app\models\TBanner;
use app\models\TBrandplan;
use app\models\TCurriculum;
use app\models\TEnterprise;
use app\models\TJoinin;
use app\models\TReview;
use app\models\TTeacherteam;
use Yii;
use app\api\components\ApiController;

class DefaultController extends ApiController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取轮播列表
     */
    public function actionGetBannerList()
    {
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $data = TBanner::find()->asArray()->orderBy('sort ASC')->all();
        foreach($data as $k=>$v){
            $data[$k]['img_url'] = $v['img_url']?Yii::$app->params['img_host'].$v['img_url']:'';
        }
        return ['code'=>self::$CODE_SUC,'msg'=>'获取数据成功','date'=>$data];

    }
    /**
     * 获取企业信息
     */
    public function actionGetEnterprise()
    {
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $data = TEnterprise::find()->asArray()->one();
            unset($data['id']);
            $data['qr_code'] = $data['qr_code']?Yii::$app->params['img_host'].$data['qr_code']:'';
            $data['logo'] = $data['logo']?Yii::$app->params['img_host'].$data['logo']:'';

        return ['code'=>self::$CODE_SUC,'msg'=>'获取数据成功','date'=>$data];

    }
    /**
     * 获取课程体系
     */
    public function actionGetCurriculum()
    {
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $data = TCurriculum::find()->asArray()->orderBy('sort ASC')->all();
        foreach($data as $k=>$v){
            $data[$k]['cover_img'] = $v['cover_img']?Yii::$app->params['img_host'].$v['cover_img']:'';

        }
        return ['code'=>self::$CODE_SUC,'msg'=>'获取数据成功','date'=>$data];
    }
    /**
     * 获取师资团队
     */
    public function actionGetTeacherteamList()
    {
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $data = TTeacherteam::find()->asArray()->orderBy('sort ASC')->all();
        foreach($data as $k=>$v){
            $data[$k]['cover_img'] = $v['cover_img']?Yii::$app->params['img_host'].$v['cover_img']:'';

        }
        return ['code'=>self::$CODE_SUC,'msg'=>'获取数据成功','date'=>$data];
    }
    /**
     * 获取品牌方案
     */
    public function actionGetBrandplan()
    {
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $data = TBrandplan::find()->asArray()->one();
//        foreach($data as $k=>$v){
//            $data[$k]['cover_img'] = $v['cover_img']?Yii::$app->params['img_host'].$v['cover_img']:'';
//
//        }
        return ['code'=>self::$CODE_SUC,'msg'=>'获取数据成功','date'=>$data];
    }
    /**
     * 获取精彩回顾
     */
    public function actionGetReview()
    {
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $data = TReview::find()->asArray()->orderBy('sort ASC')->all();
        foreach($data as $k=>$v){
            $data[$k]['cover_img'] = $v['cover_img']?Yii::$app->params['img_host'].$v['cover_img']:'';

        }
        return ['code'=>self::$CODE_SUC,'msg'=>'获取数据成功','date'=>$data];
    }
    /**
     * 在线试听
     */
    public function actionAppointment(){
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $post = Yii::$app->request->post();
        $post['create_time'] = time();
        $model = new TAppointment();
        $model->attributes = $post;
        if($model->save()) return ['code'=>self::$CODE_SUC,'msg'=>'预约成功'];
        return ['code'=>self::$CODE_ERR,'msg'=>'预约失败'];

    }
    /**
     * 申请加盟
     */
    public function actionJoinin(){
        if(!Yii::$app->request->isPost) return ['code'=>self::$CODE_ERR,'msg'=>'请求方式错误'];
        $post = Yii::$app->request->post();
        $post['create_time'] = time();
        $model = new TJoinin();
        $model->attributes = $post;
        if($model->save()) return ['code'=>self::$CODE_SUC,'msg'=>'申请加盟成功'];
        return ['code'=>self::$CODE_ERR,'msg'=>'申请加盟失败'];

    }








}