<?php

namespace app\backend\components;
use Yii;

class BaseController extends \yii\web\Controller
{
    public $layout = '@app/backend/views/layouts/main';
    public $pageSize = 15;
    public $data = ['js'=>[], 'css'=>[], 'submit'=>0, 'action_list'=>'index'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['module_id'] = $this->module->id;

        $this->data['controller_id'] = $this->id;
        $this->data['submit'] = Yii::$app->request->get('ref_sub', '0');
        $this->data['err'] = Yii::$app->request->get('err', '');
    }
    public function actionIndex()
    {
        return $this->render('index');
    }
    /**
     * 获取错误信息
     */
    public static function getModelError($model)
    {
        $errors = $model->getErrors();
        if (!is_array($errors)) return '';
        $firstError = array_shift($errors);
        if (!is_array($firstError)) return '';
        return array_shift($firstError);
    }

}
