<?php

namespace app\api\modules\home\controllers;

use app\api\modules\home\models\Article;
use app\backend\modules\txt\models\Config;
use app\models\base\BSalesAdvertisement;
use Yii;
use app\api\components\ApiController;

class DefaultController extends ApiController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * 新闻
     * @return array
     */
    public function actionIndex(){

        return ['code'=>self::$CODE_SUC];
    }







}
